os:
    - linux
#    - osx removed as there are problems with Travis installing Python
language: python
sudo: false
arch: 
    - amd64
    - arm64
python:
#    - "2.6" removed as now too old to support
    #- "2.7"
#    - "3.2" removed because Coveralls/coverage 4.0 fails on 3.2
#    - "3.3" removed as Travis apparently can't install it in a VM
    #- "3.6"
    #- "3.7"
    - "3.8"
    #- "pypy"
#             pypy was removed temporarily as coveralls isn't always fully compatible on Travis ...
#             RuntimeError: cryptography 1.9 is not compatible with PyPy < 5.3. Please upgrade PyPy to use this library.
before_install: "mkdir -p $HOME/.distlib && sudo chown -R travis:travis $HOME/.distlib || true"
# install:
    # - pip install coveralls
before_script: "whoami && ls -ld $HOME/.distlib"
script:
    - PYTHONHASHSEED=0 python setup.py test
    - uname -m
    # - if [[ $TRAVIS_PYTHON_VERSION > 2.7 ]]; then PYTHONHASHSEED=0 coverage run setup.py testd; fi
after_success: coveralls

